export const ADS_FETCH_REQUEST = 'ADS_FETCH_REQUEST';
export const ADS_FETCH_FAILURE = 'ADS_FETCH_FAILURE';
export const ADS_FETCH_SUCCESS = 'ADS_FETCH_SUCCESS';

export const AD_SAVE_REQUEST = 'AD_SAVE_REQUEST';
export const AD_SAVE_FAILURE = 'AD_SAVE_FAILURE';

export const AD_SAVE_SUCCESS = 'AD_SAVE_SUCCESS';
// export const AD_UPDATE_SUCCESS = 'AD_UPDATE_SUCCESS';
// export const AD_CREATE_SUCCESS = 'AD_CREATE_SUCCESS';

// export const SET_FILTER = 'SET_FILTER';