export const ADVERTS_FETCH_REQUEST = 'ADVERTS_FETCH_REQUEST';
export const ADVERTS_FETCH_FAILURE = 'ADVERTS_FETCH_FAILURE';
export const ADVERTS_FETCH_SUCCESS = 'ADVERTS_FETCH_SUCCESS';

export const ADVERT_SAVE_REQUEST = 'ADVERT_SAVE_REQUEST';
export const ADVERT_SAVE_FAILURE = 'ADVERT_SAVE_FAILURE';

export const ADVERT_SAVE_SUCCESS = 'ADVERT_SAVE_SUCCESS';

export const ADVERT_REMOVE_REQUEST = 'ADVERT_REMOVE_REQUEST';
export const ADVERT_REMOVE_FAILURE = 'ADVERT_REMOVE_FAILURE';
export const ADVERT_REMOVE_SUCCESS = 'ADVERT_REMOVE_SUCCESS';

export const ADVERT_QUERY_SET = 'ADVERT_QUERY_SET';
export const ADVERT_QUERY_RESET = 'ADVERT_QUERY_RESET';


export const TAGS_LOAD_REQUEST = 'TAGS_LOAD_REQUEST';
export const TAGS_LOAD_SUCCESS = 'TAGS_LOAD_SUCCESS';
export const TAGS_LOAD_FAILURE = 'TAGS_LOAD_FAILURE';