export const ADVERTS_FETCH_REQUEST = 'ADVERTS_FETCH_REQUEST';
export const ADVERTS_FETCH_FAILURE = 'ADVERTS_FETCH_FAILURE';
export const ADVERTS_FETCH_SUCCESS = 'ADVERTS_FETCH_SUCCESS';

export const ADVERT_SAVE_REQUEST = 'ADVERT_SAVE_REQUEST';
export const ADVERT_SAVE_FAILURE = 'ADVERT_SAVE_FAILURE';

export const ADVERT_SAVE_SUCCESS = 'ADVERT_SAVE_SUCCESS';
// export const ADVERT_UPDATE_SUCCESS = 'ADVERT_UPDATE_SUCCESS';
// export const ADVERT_CREATE_SUCCESS = 'ADVERT_CREATE_SUCCESS';

// export const SET_FILTER = 'SET_FILTER';